:window:
  :title: Stomp
  :width: 800
  :height: 600
  :fullscreen: false
:default_world: "Main Menu"
:common_world: "Common"
:systems:
  - init_system
  - mouse_arrow_system
  - sprite_system
  - menu_system
  - exit_system
  - scene_system
  - drag_system
  - rotation_system
  - movement_system
  - collision_system
  - gravity_system
  - force_system
  - bond_system
  - keybinding_system
  - world_system
  - damage_system
  - decay_system
  - animation_system
  - timeout_system
  - magnet_system
  - entity_system
  - condition_system

  #- debug_system
