:window:
  :title: Stomp
  :width: 800
  :height: 600
  :fullscreen: false
:default_world: "Main Menu"
:common_world: "Common"
:systems:
  - init_system
  - mouse_arrow_system
  - sprite_system
  - menu_system
  - exit_system
  - scene_system
  - drag_system

  #- debug_system
